### ISSUE TITLE
battery power

### ISSUE THREAD

**Issue by davefeilseifer** [simingl/RenoTahoe#11]
Batteries last for 18 minutes (parameterized from file) when batteries are dead, drones land and are unusable. When landing at the staging area, drones recharge after a 5-minute time-out (parameterized from file).

**Comment by simingl** [comment]
Added battery usage. When a drone is out of battery, it will land on the ground and cannot be moved anymore. Drone can move to the recharge station to recharge its battery (5 minutes from empty to full).
