### ISSUE TITLE
Multiple Drone Camera Views

### ISSUE THREAD

**Issue by davefeilseifer** [simingl/RenoTahoe#2]
Currently, only one camera view can happen for a single drone.

The operator should be able to open multiple camera views. Camera views should be closed by clicking an "x" in the top-right of the window.

**Comment by simingl** [comment]
Branch: GoogleMapVersion1.2
Commits on Aug 10/11/12, 2015
Added multiple cameras:
1. Left Shift + Left Mouse Click on a drone (Not currently controlled), camera of the drone will be activated on the top right of the screen (6 maximum). 
2. Added drone icon on the camera.
3. Add a close button on the camera.
4. Double click one of the small camera will control the corresponding drone.
5. A small camera icon is added on the top of the drone when the camera is on.

![image](https://cloud.githubusercontent.com/assets/10081279/9242515/301ee7ce-4137-11e5-8b4f-e3592eff948b.png)
