### ISSUE TITLE
camera view changes

### ISSUE THREAD

**Issue by davefeilseifer** [simingl/RenoTahoe#3]
The following changes should happen for the drone camera view:

1.) There should be 2 views, one from a front-facing camera, one from a downward-facing camera
2.) Both views should be FPV
3.) The camera view should have a picture of the drone, with the currently used camera highlighted.
4.) Clicking on the camera view should make that the currently controlled drone

**Comment by simingl** [comment]
Branch: GoogleMapVersion1.2
Commits on Aug 10/11/12, 2015
Added all the functions listed above.
