### ISSUE TITLE
in small map, show drones as small dots

### ISSUE THREAD

**Issue by davefeilseifer** [simingl/RenoTahoe#5]
no arrows are needed in this view, only show as dots. Make dots smaller than arrows are currently.

**Comment by simingl** [comment]
Changed the icon of Drone in the minimap from an arrow to a dot. The snapshot shows how it looks.

![image](https://cloud.githubusercontent.com/assets/10081279/9394615/4580eaba-473e-11e5-9795-4894be3dd998.png)
